const copy = {
  support: {
    he: ['תמיכה', `<p class="legal-note">RAVO מרכזת את מה שמחזיק בית או משרד — משימות, קניות, חשבונות ויומן — במרחב משותף. אם משהו לא עובד כצפוי, אנחנו כאן.</p><h2>איך פונים אלינו?</h2><p>שלחו מייל אל <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. אנחנו משתדלים להשיב בתוך יום עסקים.</p><p>כדי שנוכל לעזור מהר, כתבו מה ניסיתם לעשות, מה קרה במקום ומאיזה מכשיר. אין צורך לשלוח תוכן פרטי, סיסמאות או פרטי תשלום.</p><h2>שאלות נפוצות</h2><h3>שכחתי סיסמה</h3><p>במסך הכניסה למוצר אפשר לבקש איפוס סיסמה ולקבל קוד בדוא״ל.</p><h3>הזמנה לא עובדת</h3><p>הזמנה תקפה לשבעה ימים ומיועדת לכתובת שאליה נשלחה. אם פגה, בקשו מבעל המרחב לשלוח חדשה.</p><h3>איך מוחקים חשבון?</h3><p>מחיקת חשבון זמינה מתוך הגדרות המוצר ומתבצעת מיד. אין צורך לפנות לתמיכה.</p>`],
    en: ['Support', `<p class="legal-note">RAVO brings together the things that keep a home or office running. If something isn’t working as expected, we’re here.</p><h2>Contact us</h2><p>Email <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. We aim to reply within one business day.</p><p>Tell us what you tried, what happened instead, and which device you used. Please don’t send private household content, passwords or payment details.</p><h2>Common questions</h2><h3>Forgotten password</h3><p>The product’s sign-in screen can send a password-reset code by email.</p><h3>An invitation doesn’t work</h3><p>Invitations remain valid for seven days and are tied to their recipient address. If one expires, ask the workspace owner to send a new one.</p><h3>Deleting an account</h3><p>Account deletion is available in product settings and takes effect immediately. Support contact is not required.</p>`]
  },
  privacy: {
    he: ['מדיניות פרטיות', `<p class="legal-note">המדיניות מתארת איזה מידע RAVO שומרת כדי להפעיל מרחב ביתי או משרדי משותף, ואיזה מידע אינה אוספת.</p><h2>המידע שנשמר</h2><p><strong>חשבון:</strong> כתובת דוא״ל, סיסמה שמנוהלת באופן מוצפן על ידי שירות האימות, שם תצוגה ותפקיד במרחב.</p><p><strong>תוכן המרחב:</strong> משימות, קניות, מזווה, ארוחות, חשבונות, אירועי יומן, התראות ותוכן משרדי שהמשתמשים בוחרים להוסיף.</p><p><strong>מידע טכני:</strong> פרטי מכשיר הנדרשים להתראות, ודיווחי תקלה טכניים שמנוקים מתוכן אישי ככל האפשר.</p><h2>למה המידע משמש</h2><p>רק להפעלת השירות: סנכרון בין חברי המרחב, אכיפת הרשאות, הצגת מידע והתראות. תוכן המרחב אינו משמש לפרסום או לאימון מודלים.</p><h2>מה איננו עושים</h2><p>איננו מוכרים מידע אישי, איננו מציגים פרסומות, איננו מבצעים פרסום ממוקד ואיננו משתמשים בעוגיות מעקב של צד שלישי באתר הציבורי.</p><h2>מי רואה מה</h2><p>הגישה מבוססת חשבון, חברות במרחב והרשאות. ההרשאות נאכפות במסד הנתונים ואין גישה בין מרחבים נפרדים.</p><h2>ספקי תשתית</h2><p>השירות משתמש בספקי תשתית לאימות, אחסון נתונים, סנכרון, שליחת דוא״ל, התראות וניטור תקלות. מידע עשוי להישמר מחוץ לישראל לצורך הפעלת השירות.</p><h2>שמירה, זכויות ומחיקה</h2><p>המידע נשמר כל עוד החשבון קיים ובהתאם לצורכי השירות. אפשר לעיין ולתקן פרטים במוצר ולמחוק חשבון מתוך ההגדרות. לבקשת עותק או שאלה כתבו אל <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>.</p><h2>אבטחה</h2><p>התקשורת מוצפנת, סיסמאות אינן נשמרות אצל RAVO כטקסט ומפתחות בעלי הרשאות מוגברות אינם נשלחים למכשיר. אף שירות אינו חסין לחלוטין.</p>`],
    en: ['Privacy Policy', `<p class="legal-note">This policy explains the information RAVO keeps to operate a shared household or office workspace, and what it does not collect.</p><h2>Information kept</h2><p><strong>Account:</strong> email address, a password handled in encrypted form by the authentication provider, display name and workspace role.</p><p><strong>Workspace content:</strong> tasks, shopping, pantry, meals, bills, calendar events, notifications and office content users choose to add.</p><p><strong>Technical information:</strong> device details needed for notifications and technical error reports stripped of personal content where possible.</p><h2>Purpose</h2><p>Information is used to operate the service: syncing members, enforcing permissions, displaying information and sending notifications. Workspace content is not used for advertising or model training.</p><h2>What we don’t do</h2><p>We don’t sell personal information, display advertising, run targeted advertising or use third-party tracking cookies on this public website.</p><h2>Access</h2><p>Access depends on an account, workspace membership and permissions enforced in the database. Separate workspaces cannot access each other.</p><h2>Infrastructure providers</h2><p>RAVO uses providers for authentication, data storage, synchronisation, email, notifications and error monitoring. Information may be processed outside Israel to operate the service.</p><h2>Retention and your rights</h2><p>Information is kept while the account exists and as needed to operate the service. Details can be viewed and corrected in the product, and accounts can be deleted in settings. For a copy or a question, email <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>.</p><h2>Security</h2><p>Transport is encrypted, passwords are not stored by RAVO as plain text and privileged keys are not sent to devices. No service can promise absolute security.</p>`]
  },
  terms: {
    he: ['תנאי שימוש', `<p class="legal-note">RAVO נמצאת כעת בשלב טרום־השקה ומסופקת ללא תשלום. תנאי תשלום יחולו רק אם וכאשר יופעל שירות בתשלום, לאחר הודעה מראש.</p><h2>השירות</h2><p>RAVO מסייעת לבית או למשרד קטן לתאם משימות, קניות, יומן, חשבונות ותפעול משותף. היא אינה שירות בנקאי, ייעוץ פיננסי, רפואי או שירות חירום.</p><h2>חשבון ואחריות</h2><p>המשתמשים אחראים למסור פרטים נכונים, לשמור על סודיות אמצעי הגישה ולהוסיף למרחב רק אנשים ומידע שיש להם רשות להוסיף. בעל המרחב אחראי לבחירת תפקידים והרשאות.</p><h2>שימוש הוגן</h2><p>אין להשתמש בשירות באופן בלתי חוקי, לפגיעה באחרים, להפרת פרטיות, להפצת קוד מזיק או לניסיון לעקוף הרשאות.</p><h2>זמינות ושינויים</h2><p>זהו שירות בשלבי פיתוח. ייתכנו שינויים, הפסקות ותקלות. נשאף לשמור על מידע ועל רציפות, אך אין להסתמך על RAVO למקרה שבו תקלה עלולה לגרום נזק ממשי.</p><h2>קניין רוחני</h2><p>המשתמשים שומרים על הזכויות בתוכן שהם מוסיפים. השם RAVO, המיתוג והתוכנה שייכים למפעיל השירות.</p><h2>יצירת קשר</h2><p>לשאלות כתבו אל <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. פרטי המפעיל המסחריים המלאים יפורסמו לפני כל השקה בתשלום.</p>`],
    en: ['Terms of Use', `<p class="legal-note">RAVO is currently preparing for release and is provided without charge. Payment terms will apply only if a paid service is introduced, after advance notice.</p><h2>The service</h2><p>RAVO helps a household or small office coordinate tasks, shopping, calendar, bills and shared operations. It is not banking, financial or medical advice, or an emergency service.</p><h2>Accounts and responsibility</h2><p>Users must provide accurate details, protect their access credentials, and add only people and information they are authorised to add. Workspace owners are responsible for roles and permissions.</p><h2>Fair use</h2><p>The service may not be used unlawfully, to harm others, violate privacy, distribute malicious code or circumvent permissions.</p><h2>Availability and changes</h2><p>This service remains in development. Changes, interruptions and faults may occur. RAVO should not be relied upon where a failure could cause material harm.</p><h2>Intellectual property</h2><p>Users retain rights in content they add. The RAVO name, brand and software belong to the service operator.</p><h2>Contact</h2><p>Questions can be sent to <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. Full commercial operator details will be published before any paid launch.</p>`]
  },
  accessibility: {
    he: ['הצהרת נגישות', `<p class="legal-note">RAVO נבנית עבור בית שלם — כולל אנשים שרואים, שומעים או מפעילים מכשיר אחרת. ההתאמה נמשכת והאתר טרם עבר ביקורת נגישות מוסמכת.</p><h2>מה נעשה באתר</h2><ul><li>מבנה סמנטי וכותרות ברורות.</li><li>ניווט מקלדת ומיקוד נראה.</li><li>ניגודיות וטקסט חלופי לתמונות מוצר.</li><li>עברית מימין לשמאל ואנגלית משמאל לימין.</li><li>שטחי הפעלה נדיבים והתאמה למסכים קטנים.</li><li>כיבוד העדפת המערכת להפחתת תנועה.</li></ul><h2>מה עדיין לא נבדק</h2><p>לא בוצעה ביקורת חיצונית מלאה או בדיקה מקיפה בכל קוראי המסך והמכשירים. לכן איננו מצהירים על הסמכה או התאמה מלאה לתקן.</p><h2>דרך חלופית ופניות</h2><p>אם תוכן מסוים אינו נגיש לכם, כתבו אל <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. נשמח לספק מידע בדרך חלופית ולטפל בליקוי.</p>`],
    en: ['Accessibility Statement', `<p class="legal-note">RAVO is being built for a whole household — including people who see, hear or operate a device differently. Accessibility work is ongoing and the site has not had a certified audit.</p><h2>What the website supports</h2><ul><li>Semantic structure and clear headings.</li><li>Keyboard navigation and visible focus.</li><li>Colour contrast and alternative text for product imagery.</li><li>Right-to-left Hebrew and left-to-right English.</li><li>Generous touch targets and small-screen layouts.</li><li>Respect for reduced-motion system preferences.</li></ul><h2>What hasn’t been fully tested</h2><p>No complete external audit or exhaustive testing across every screen reader and device has taken place. We therefore do not claim certification or full standards conformance.</p><h2>Alternative access and contact</h2><p>If any content is inaccessible, email <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>. We’ll provide an alternative format and work to fix the issue.</p>`]
  },
  'subscription-policy': {
    he: ['מדיניות מנוי וביטול', `<p class="legal-note">אין כרגע מנוי בתשלום. מחיר סופי, תקופת חיוב ותנאים מסחריים יפורסמו לפני הפעלה של שירות בתשלום.</p><h2>כל עוד השירות ללא תשלום</h2><p>לא מתבצע חיוב, אין חידוש אוטומטי ואין צורך לבטל מנוי.</p><h2>אם יופעל מנוי בעתיד</h2><p>המחיר ותדירות החיוב יוצגו לפני אישור רכישה. כל חידוש אוטומטי, דרך הביטול וזכויות החזר יוסברו לפני התשלום ובהתאם לדין ולכללי פלטפורמת הרכישה.</p><h2>מה קורה למידע</h2><p>ביטול מנוי עתידי לא ימחק חשבון או תוכן באופן אוטומטי. מחיקת חשבון תהיה פעולה נפרדת מתוך הגדרות המוצר.</p><h2>שאלות</h2><p>כתבו אל <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>.</p>`],
    en: ['Subscription & Cancellation Policy', `<p class="legal-note">There is currently no paid subscription. Final pricing, billing period and commercial terms will be published before any paid service begins.</p><h2>While the service is free</h2><p>No charge is made, there is no automatic renewal and there is no subscription to cancel.</p><h2>If a subscription is introduced</h2><p>Price and billing frequency will be shown before purchase. Any auto-renewal, cancellation method and refund rights will be explained before payment, in line with applicable law and the purchase platform’s rules.</p><h2>Your information</h2><p>Cancelling a future subscription will not automatically delete an account or its content. Account deletion will remain a separate action in product settings.</p><h2>Questions</h2><p>Email <a href="mailto:support@ravoapp.app">support@ravoapp.app</a>.</p>`]
  }
}

const key = document.body.dataset.page
const switcher = document.querySelector('[data-lang-switch]')
function render(language) {
  const [title, html] = copy[key][language]
  document.documentElement.lang = language
  document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr'
  document.title = `${title} — RAVO`
  document.querySelector('h1').textContent = title
  document.querySelector('.legal-content').innerHTML = html
  document.querySelector('[data-back]').textContent = language === 'he' ? 'חזרה לאתר' : 'Back to website'
  document.querySelector('[data-updated]').textContent = language === 'he' ? 'עודכן: 6 בספטמבר 2026' : 'Updated: 6 September 2026'
  switcher.textContent = language === 'he' ? 'EN' : 'עברית'
  localStorage.setItem('ravo-marketing-language', language)
}
render(localStorage.getItem('ravo-marketing-language') === 'en' ? 'en' : 'he')
switcher.addEventListener('click', () => render(document.documentElement.lang === 'he' ? 'en' : 'he'))
